### ISSUE TITLE
看了前两章的内容，以下提到的部分建议稍作修改。

### ISSUE THREAD

**Issue by GHyingchao** [BillowsTao/Front-End-Knowledge-Base#6]
看了前两章的内容，以下提到的部分建议稍作修改。
1. 题目没有链接
2. 开头少目录表
3.背景：本文档定义了 HTML 和 CSS 的格式和规约（样式）规则。。。。。。最后一句有歧义。
4. 协议：嵌入式资源中尽可能使用HTTPS。
5. 一般元规则：通过指定HTML模板和文档中的编码<meta charset="utf-8">   改成通过<>指定。。。
6. 尽可能按需解释代码
7. 注释部分：对于HTML和CSS代码，注释的必要性可能会有很大差异，并取决于项目的复杂性。   改成  这取决于项目的复杂性
8.行为项：
    改成用TODO标记代办事项和动作项。注意两点：1.两个名称要统一 2. 用什么标记
    仅使用关键字TODO突出显示。。。
    使用如下格式在括号中添加联系人    TODO(contact)
    冒号：如。。。所示，去掉中
9. HTML：
   文档类型：括号中，改成优化空间比HTML小。

**Comment by BillowsTao** [comment]
> 看了前两章的内容，以下提到的部分建议稍作修改。
> 
> 1. 题目没有链接
> 2. 开头少目录表
>    3.背景：本文档定义了 HTML 和 CSS 的格式和规约（样式）规则。。。。。。最后一句有歧义。
> 3. 协议：嵌入式资源中尽可能使用HTTPS。
> 4. 一般元规则：通过指定HTML模板和文档中的编码   改成通过<>指定。。。
> 5. 尽可能按需解释代码
> 6. 注释部分：对于HTML和CSS代码，注释的必要性可能会有很大差异，并取决于项目的复杂性。   改成  这取决于项目的复杂性
>    8.行为项：
>    改成用TODO标记代办事项和动作项。注意两点：1.两个名称要统一 2. 用什么标记
>    仅使用关键字TODO突出显示。。。
>    使用如下格式在括号中添加联系人    TODO(contact)
>    冒号：如。。。所示，去掉中
> 7. HTML：
>    文档类型：括号中，改成优化空间比HTML小。

1. 第 1, 2 点已讨论，编辑器与 Markdown 支持目录显示，源文档也存在目录，因此不需要修改。
2. `3. 背景...有歧义。`  已修改。
```text
本文档定义了 HTML 和 CSS 的格式和样式规则。它的目标是提高协作、代码质量和支持基础设备。它适用于包括 GSS 文件在内的使用 HTML 和 CSS 的源文件。只要保持一致的代码质量，工具就可以自由地混淆、缩小和编译源代码。
```
3. `协议：...HTTPS。` 已修改。
```text
嵌入式资源尽可能使用 HTTPS 协议。
```
4. `一般元规则：通过指定HTML模板和文档中的编码 改成通过<>指定。。。` 已修改。
```text
通过 HTML 模板和文档中的编码 `<meta charset="utf-8">` 指定。不要指定样式表的编码，因为它们采用 UTF-8。
```
5. `5. 尽可能按需解释代码` 保留原翻译。
```text
Explain code as needed, where possible.
尽可能解释代码。
```
5. `6. 注释部分：... 改成  这取决于项目的复杂性` 已修改。
```text
（这个选项是可选的，因为总是要求完整的文档化代码是不现实的。对于HTML和CSS代码，可能会有很大的不同，这取决于项目的复杂性。）
```
6. 一般元原则，已修改
```text
通过 HTML 模板和文档中的编码 `<meta charset="utf-8">` 指定。不要指定样式表的编码，因为它们采用 UTF-8。
（这个选项是可选的，因为总是要求完整的文档化代码是不现实的。对于HTML和CSS代码，可能会有很大的不同，这取决于项目的复杂性。）
```
7. 行为项，已修改。
```text
用 `TODO` 标记待办事项和动作项。

使用关键字 `TODO` 突出显示待办事项，而不使用其他常见格式（如 `@@`）。

在括号中添加联系人（用户名或邮件列表） `TODO(contact)`。

在冒号后附加操作项，如 `TODO: 待办事情`。
```
8. HTML 5，已修改
```text
（建议使用 HTML，例如 `text/html`。不要使用 XHTML。XHTML, `application/xhtml+xml` 既缺乏浏览器基础结构支持，优化空间比 HTML 小。）
```
