### ISSUE TITLE
翻译文本建议修改

### ISSUE THREAD

**Issue by GHyingchao** [BillowsTao/Front-End-Knowledge-Base#7]
HTML章节-最后
1. 多媒体后备
     （1）“对于通过的图像，视频，canvas 动画，确保提供其他访问权限。”  
改成“对于多媒体，请确保其他访问方式。例如图像、视频、动画对象可使用canvas”
     （2）A blind user翻译成盲人不太好，建议改成“不会使用的开发者”
2. HTML格式
    （1）通用格式下
            “此外，缩进块，列表或表元素的子元素。”改成 “如果是块，列表或表元素的子元素，请进行缩进”

**Comment by BillowsTao** [comment]
> HTML章节-最后
> 
> 1. 多媒体后备
>    （1）“对于通过的图像，视频，canvas 动画，确保提供其他访问权限。”
>    改成“对于多媒体，请确保其他访问方式。例如图像、视频、动画对象可使用canvas”
>    （2）A blind user翻译成盲人不太好，建议改成“不会使用的开发者”
> 2. HTML格式
>    （1）通用格式下
>    “此外，缩进块，列表或表元素的子元素。”改成 “如果是块，列表或表元素的子元素，请进行缩进”

1. 多媒体后备，已修改
```text
"For multimedia, such as images, videos, animated objects via canvas, make sure to offer alternative access. For images that means use of meaningful alternative text (alt) and for video and audio transcripts and captions, if available."

对于多媒体，如图像、视频、通过 `canvas` 生成的动画对象，一定要提供可选的访问方式。对于图像，这意味着使用有意义的替代文本(`alt`)和视频，音频字幕（如果可用）。

Providing alternative contents is important for accessibility reasons: A blind user has few cues to tell what an image is about without @alt, and other users may have no way of understanding what video or audio contents are about either.

由于可访问性的原因，提供替代内容是很重要的：没有 `@alt`，盲人用户很难知道图像是关于什么的，其他用户可能也无法理解视频或音频内容是关于什么的。
```
2. `“此外，缩进块，列表或表元素的子元素。”改成 “如果是块，列表或表元素的子元素，请进行缩进”` 已修改
```text
缩进块，列表或表元素的子元素也进行缩进。
```

**Comment by BillowsTao** [comment]
1. 多媒体后备，再修改一下
```text
对于多媒体，如图像、视频等通过 `canvas` 生成的动画对象，一定要提供可选的访问方式。对于图像，这意味着使用有意义的替代文本(`alt`)和视频，音频字幕（如果可用）。
```
